### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by mwatts15** [openworm/owmeta#458]
# Summary
This issue tracks the completion of issues targeted for release 1.0.

## Features/changes with development in progress planned for R1

- [x] Data packaging with bundles (create, simple query, local install, deploy,
  fetch remote) (#464)
- [x] SQLite storage for local database (this is an option, but switched to the ZODB 5 store since it performs better on load) 
- [x] Improve initial insert performance (e.g., through bulk loading) _Resolved by upgrading to ZODB 5 - drastic improvement in load times and disk space usage_
- [ ] ~Lazy graph deserialization~
  - [ ] ~Don't load in graphs until they're requested~
- [x] Rename PyOpenWorm to ow-meta (#461)
- [x] Split ow-meta into ow-meta and ow-meta-core sub projects (#462)
- [x] Use standard platform-dependent dependencies (PEP 508) in setup.py (#459)

## ow-meta / ow-meta-core split

Here's how the split will look:
* ow-meta will have most of the DataObject sub-classes specific to OpenWorm
 (biological details, documents, evidence), some of the sub-commands to
 POW (to be renamed as OWM), and the data-source-specific DataTranslator
 and DataSource implementations
* ow-meta-core will have DataObject and supporting classes, the generic
 parts of the POW command and sub-commands

This split allows to reuse ow-meta-core outside of ow-meta and even outside the
OpenWorm projects as a generic RDF-Python object mapper.

**Comment by mwatts15** [comment]
Dropping lazy graph deserialization. Ends up not being an effective way to constrain load times.

**Comment by mwatts15** [comment]
Decided not to make the next release 1.0: will instead be another `0.N.0` release. This is to allow for potential adjustments to the interface needed during integration with other OpenWorm projects without requiring migration guides and explicit tracking of interface compatibility which we'd otherwise hold ourselves to. Nonetheless, the interface for the next release isn't expected to have breaking changes, just extensions.
